import {
  Shield,
  ShieldCheck,
  Search,
  Zap,
  Handshake,
  CheckCircle2,
  Phone,
  MessageCircle,
  Mail,
  Menu,
  X,
  ChevronDown,
  GraduationCap,
  Wrench,
  FileText,
  Languages,
  Plane,
  Users,
  Globe,
  Building2,
  Clock,
  Package,
  Target,
  Repeat,
  ClipboardList,
  Lock,
  BookText,
  Quote,
  User,
  Factory,
  Stethoscope,
  HardHat,
  UtensilsCrossed,
  ChefHat,
  ShoppingBag,
  Folder,
  Code2,
  Compass,
  Fuel,
  Car,
  Sparkles,
  Truck,
  Cog,
  BadgeCheck,
  Flame,
  Hammer,
  Droplets,
  BedDouble,
  HeartHandshake,
  Wheat,
  Box,
  Plus,
  MapPin,
} from "lucide-react";

export const icons = {
  shield: Shield,
  "shield-check": ShieldCheck,
  search: Search,
  zap: Zap,
  handshake: Handshake,
  "check-circle": CheckCircle2,
  phone: Phone,
  "message-circle": MessageCircle,
  mail: Mail,
  menu: Menu,
  x: X,
  "chevron-down": ChevronDown,
  "graduation-cap": GraduationCap,
  wrench: Wrench,
  "file-text": FileText,
  languages: Languages,
  plane: Plane,
  users: Users,
  globe: Globe,
  "building-2": Building2,
  clock: Clock,
  package: Package,
  target: Target,
  repeat: Repeat,
  "clipboard-list": ClipboardList,
  lock: Lock,
  "book-text": BookText,
  quote: Quote,
  user: User,
  factory: Factory,
  stethoscope: Stethoscope,
  "hard-hat": HardHat,
  "utensils-crossed": UtensilsCrossed,
  "chef-hat": ChefHat,
  "shopping-bag": ShoppingBag,
  folder: Folder,
  code: Code2,
  compass: Compass,
  fuel: Fuel,
  car: Car,
  sparkles: Sparkles,
  truck: Truck,
  cog: Cog,
  "badge-check": BadgeCheck,
  flame: Flame,
  hammer: Hammer,
  droplets: Droplets,
  bed: BedDouble,
  "heart-handshake": HeartHandshake,
  wheat: Wheat,
  box: Box,
  plus: Plus,
  "map-pin": MapPin,
};
